version: '3'

services:
  app:
    image: o3cloudng/xzeety:dev
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
#
            #  python3 manage.py wait_for_db &&
    # env_file:
    #   - ./.env
    # depends_on:
    #   - db

  # db:
  #   image: postgres:11-alpine
  #   env_file:
  #     - ./.env
  #   volumes: 
  #     - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l info
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - redis
      - app
# volumes:
#   pgdata: